import "./globals.css";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { NextUIProvider } from "@nextui-org/system";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import "../app/styles/style.css";
import "../app/styles/accordion.css";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} id="dark">
        <NextUIProvider>
          <Header />
            {children}
          <Footer />
        </NextUIProvider>
      </body>
    </html>
  );
}
